import Head from 'next/head';
import Image from 'next/image';
import coffeeStores from '../coffee-stores.json';
import Banner from '../components/Banner';
import Card from '../components/Card';
import styles from '../styles/Home.module.css';
export default function Home(props) {
  const handleClick = () => {
    console.log('hi');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffe Connoissuer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View Stores nearby" handleClick={handleClick} />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="hero"
            about="hero"
            width={700}
            height={400}
          />
        </div>
        {props.coffeeStores.length > 0 && (
          <h2 className={styles.heading2}>Toronto stores</h2>
        )}
        <div className={styles.cardLayout}>
          {props.coffeeStores.map((store) => (
            <Card
              key={store.id}
              name={store.name}
              href={`/coffee-store/${store.id}`}
              imgUrl={store.imgUrl}
            />
          ))}
        </div>
      </main>
    </div>
  );
}
export async function getStaticProps() {
  return {
    props: {
      coffeeStores,
    },
  };
}
